services:
  val-db-dev:
    container_name: val-db-dev
    image: postgres:16.8-alpine
    volumes:
      - ./.docker/postgres-localhost/data:/var/lib/postgresql/data
      - ./docker/postgres-localhost/install-extensions.sql:/docker-entrypoint-initdb.d/install-extensions.sql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U val_local -d val_local" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
