services:
  db:
    container_name: db
    image: postgres:16.8-alpine
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/install-extensions.sql:/docker-entrypoint-initdb.d/install-extensions.sql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=val
      - POSTGRES_USER=val
      - POSTGRES_SCHEMA=val
      - POSTGRES_PASSWORD=val