name: valenstagram-backend

services:
  val-db:
    container_name: val-db
    image: postgres:16.8-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/install-extensions.sql:/docker-entrypoint-initdb.d/install-extensions.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  val-api:
    container_name: val-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${API_ENV}
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:5000"
    environment:
      # Configuration Flask
      DOCKER_CONTAINER: "true"
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${API_ENV}
      API_ENV: ${API_ENV}
      
      # Configuration base de données
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@val-db:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
      # Configuration sécurité
      SECRET_KEY_APP: ${SECRET_KEY_APP}
      SECRET_KEY_JWT: ${SECRET_KEY_JWT}
      
      # Configuration serveur
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      WORKERS: ${WORKERS}
      
      # Configuration Swagger
      SWAGGER_URL: ${SWAGGER_URL:-/api/docs}
      API_URL: ${API_URL:-/static/openapi.json}
      
      # Mode production
      FLASK_PROD: ${FLASK_PROD:-true}

      DB_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@val-db:5432/${POSTGRES_DB}
      DB_URI_DEV: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@val-db:5432/${POSTGRES_DB}
    volumes:
      - uploads_data:/app/public/uploads
      - ./logs:/app/logs
    depends_on:
      val-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  backend:
    driver: bridge
    internal: true
  frontend:
    driver: bridge