"""test migration

Revision ID: 82e9d6fc5c96
Revises: 1ba93ff69fd5
Create Date: 2025-08-21 23:39:55.885134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e9d6fc5c96'
down_revision: Union[str, Sequence[str], None] = '1ba93ff69fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'updated_at')
    # ### end Alembic commands ###
